
# 로컬 모드 설정
spring.config.activate.on-profile: local

spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3307/hope-gaarden?serverTimezone=Asia/Seoul
    username: jus
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        query:
          in_clause_parameter_padding: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace