name: Back-test

on:
  pull_request:
    branches: [dev]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # application.yml 파일 설정
      - name: resources 폴더 생성
        run: |
          mkdir -p ./Back/src/main/resources

      - name: yml 파일 생성
        run: |
          echo "${{ secrets.DATABASE }}" > ./Back/src/main/resources/application.yml

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'hope-gaaden' 
          mysql user: 'jus'
          mysql password: ${{ secrets.MYSQL_PASSWORD }}
        
      - name: Grant execute permission for gradlew
        run: chmod +x ./Back/gradlew
        
      - name: Test with Gradle
        run: |
          cd ./Back
          ./gradlew test